name: archive
run-name: Archive Websites
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
    - cron: "0 6 * * *"
    - cron: "0 12 * * *"
    - cron: "0 18 * * *"
jobs:
  Archive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: browser-actions/setup-chrome@latest
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - run: EXIT_CODE=$(python main.py)
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A
          git diff-index --quiet HEAD || git commit -am "archived"
          git push
      - run: exit $EXIT_CODE
